/**
* @File Name : UserPresenceController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : June 23, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | June 23, 2025 |   | Initial Version
**/

public class UserPresenceController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}